### ISSUE TITLE
How to use Enum8/Enum16?

### ISSUE THREAD

**Issue by Zarathustra2** [plausible/chto#42]
Hey, 

I couldn't find any types for Enum8/Enum16. 

How would I create an Ecto schema for a table having columns with types Enum8/Enum16? Or is this missing and needs to be added?

Best regards,
Dario

**Comment by ruslandoga** [comment]
@Zarathustra2 👋

That's right. It's missing. I'll add them tomorrow.

**Comment by Zarathustra2** [comment]
That would be awesome! :)

**Comment by ruslandoga** [comment]
I'm working on replacing all custom types with a single one which takes string ClickHouse type as the parameter. So enums would be defined like so:

```elixir
field :some_enum, Ch, type: "Enum('hello' = 1, 'world' = 2)"
```

**Comment by Zarathustra2** [comment]
oh wow, that looks awesome!

**Comment by Zarathustra2** [comment]
With the current types how would I be able to define a nullable field with the Decimal type:  

```elixir
# This isn't syntactically correct 
field(:iv_high,  Ch.Types.Nullable , type: Ch.Types.Decimal64, scale: 4)
```

I assume with the new types it would just be:
```elixir
field(:iv_high, Ch, type: "Nullable(Decimal64(4))")
```

but for the old types I cannot figure it out for my tests

**Comment by ruslandoga** [comment]
maybe `field :iv, Ch.Types.Nullable, type: Ch.Types.Decimal64.init(scale: 4)

**Comment by ruslandoga** [comment]
```elixir
field :iv_high, Ch, type: "Nullable(Decimal64(4))"
```
should work now.

**Comment by Zarathustra2** [comment]
I think this can be closed, no?

**Comment by ruslandoga** [comment]
I guess so. I'll close it today once the tests branch is merged. I wanted to leave the links with usage examples for these types.

**Comment by ruslandoga** [comment]
Enum example: https://github.com/plausible/chto/blob/c76b7790ec6a5dbe48a92cda3125d32868f87d14/test/ch/type_test.exs#L655-L689

Nullable example: https://github.com/plausible/chto/blob/c76b7790ec6a5dbe48a92cda3125d32868f87d14/test/ch/type_test.exs#L950-L1058
